### ISSUE TITLE
MatterMost doesn't like @mentions in messages

### ISSUE THREAD

**Issue by NielsVanHoef** [orbitalimpact/hipmost#3]
Running the convert will take the messages as-is, running the import will produce errors for each message which has an @username mention in it. Removing the @ from the jsonl file will solve the problem and allow an import of the data.

**Comment by davidbartonau** [comment]
I am no seeing that.  I have converted all my usernames to lowercase and it seems to be working.  The @mentions also seem to convert as I don't think they are case sensitive.

**Comment by davidbartonau** [comment]
The key thing is to import ALL your users first and THEN import messages.  I added a new command to do this in my merge request #4  and stepped through the process in Commands.ods

**Comment by gabrielrios** [comment]
@NielsVanHoef can you confirm if it still happening after @davidbartonau fixes?

**Comment by NielsVanHoef** [comment]
@gabrielrios I can confirm the problem has been solved with this fix. Thx!
